name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pip-audit

    - name: Run integration tests
      run: |
        pytest tests/test_integration.py

    - name: Dependency vulnerability check
      run: |
        pip-audit

    - name: Run UI tests
      run: |
        pytest tests/test_ui.py